<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php 
        foreach($monCss as $value){
            echo('<link rel="stylesheet" href="'.$value.'">');
        }
    ?>
    <title>Cinéthèque</title>
</head>
<body>
    <header>
        <nav>
            <section class= "title">
                <img src="./img/logo.png" alt="Logo">
                <h1>Ma Cinéthèque</h1>
            </section>
            <form action="search.php" method="get">
                <input type="search" name="recherche">
                <button>Rechercher</button>
            </form>
            <ul>
                <li><a href="list.php">Liste</a></li>
                <li><a href="add.php">Ajouter</a></li>
                <?php 
                    $info = file_get_contents("login.json");
                    $tabInfo = json_decode($info, true);
                    if($tabInfo['login'] == false){
                        echo("<li><a href=\"login.php\">Login</a></li>");
                    }
                    else{
                        echo("
                        <li><a href=\"login.php\">Admin</a></li>
                        <form action=\"deco.php\" method=\"get\">
                        <button>Deconnexion<button>
                        </form>
                        ");
                    }
                ?>
            </ul>
        </nav>
    </header>
