<main>
    <h2>Login</h2>
    <div class="container">
        <form action="login.php" method="get" class="formLog">
            <div class="divInp">
                <label for="user">Nom d'utilisateur:</label>
                <input type="text" name="user">
            </div>
            <div class="divInp">
                <label for="pass">Mot de passe:</label>
                <input type="password" name="pass">
            </div>
            
            <button>Se connecter</button>
        </form>

